global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - performance/prometheus/rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [backend:8081]

  - job_name: nginx
    static_configs:
      - targets: [nginx:80]
