name: Deploy

on:
  push:
    branches:
      - main   # troca para master se a tua branch principal for master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy stack with Docker Compose
        run: |
          # já estamos no diretório do repo na VM

          # Garantir volumes de monitoring / db
          docker volume create postgres_data || true
          docker volume create prometheus_data || true
          docker volume create grafana_data || true

          # Subir TODOS os serviços do docker-compose.yml
          docker compose pull || docker-compose pull
          docker compose up -d --build || docker-compose up -d --build
